name: MapReduce script

on: push # выполнится при пуше на любых ветках

jobs:
  build-test:
    # последняя версия не всегда стабильна
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      # совсем устаревшие версии actions
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: Install dependencies
      # хардирование пакетов для установки
      # отсутствие кэширования
      run: |
        pip install flake8 pytest mrjob

    - name: Lint code
      # линтинг не остановит пайплайн при наличии ошибок
      run: |
        flake8 .lab3/ --exit-zero

    - name: Test with pytest
      run: |
        pytest
    
  deploy:
    runs-on: ubuntu-latest
    # хранение секретных данных в открытом доступе
    env:
        DOCKER_HUB_USERNAME: staffeev
        DOCKER_HUB_TOKEN: dckr_pat_rLeRy6m8wfDjmWFqfP_IwQ9LJcg
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/mapreduce_script:latest


