name: MapReduce script

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint code
      run: |
        flake8 ./lab3 --count --statistics --show-source
    
  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:

    - name: Test with pytest
      run: |
        pytest

  deploy:
    runs-on: ubuntu-20.04
    needs: test
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mapreduce_script:$(date-'%Y-%m-%d %H-%M-%S')

