FROM ubuntu:latest
FROM python:latest

ENV testfile test.sh

RUN apt-get update -y > /dev/null && apt-get upgrade -y > /dev/null
RUN apt-get install bash neofetch -y > /dev/null
ADD . .
RUN bash $testfile
RUN python3 test.py
